PARAMS = {
    'pong': {
        'env_name':         "PongNoFrameskip-v4",
        'stop_reward':      18.0,
        'run_name':         'pong',
        'replay_size':      100000,
        'replay_initial':   10000,
        'target_net_sync':  1000,
        'epsilon_frames':   10**5,
        'epsilon_start':    1.0,
        'epsilon_final':    0.02,
        'prio_replay_alpha': 0.6,
        'beta_start':       0.4,
        'beta_frames':      100000,
        'n_steps':          3,
        'learning_rate':    0.0001,
        'gamma':            0.99,
        'batch_size':       32
    },
    'breakout-small': {
        'env_name':         "BreakoutNoFrameskip-v4",
        'stop_reward':      500.0,
        'run_name':         'breakout-small',
        'replay_size':      3*10 ** 5,
        'replay_initial':   20000,
        'target_net_sync':  1000,
        'epsilon_frames':   10 ** 6,
        'epsilon_start':    1.0,
        'epsilon_final':    0.1,
        'prio_replay_alpha': 0.6,
        'beta_start':       0.4,
        'beta_frames':      100000,
        'n_steps':          3,
        'learning_rate':    0.0001,
        'gamma':            0.99,
        'batch_size':       64
    },
    'breakout': {
        'env_name':         "BreakoutNoFrameskip-v4",
        'stop_reward':      500.0,
        'run_name':         'breakout',
        'replay_size':      10 ** 6,
        'replay_initial':   50000,
        'target_net_sync':  10000,
        'epsilon_frames':   10 ** 6,
        'epsilon_start':    1.0,
        'epsilon_final':    0.1,
        'prio_replay_alpha': 0.6,
        'beta_start':       0.4,
        'beta_frames':      100000,
        'n_steps':          3,
        'learning_rate':    0.00025,
        'gamma':            0.99,
        'batch_size':       32
    },
    'invaders': {
        'env_name': "SpaceInvadersNoFrameskip-v4",
        'stop_reward': 500.0,
        'run_name': 'invaders',
        'replay_size': 10 ** 6,
        'replay_initial': 50000,
        'target_net_sync': 10000,
        'epsilon_frames': 10 ** 6,
        'epsilon_start': 1.0,
        'epsilon_final': 0.1,
        'prio_replay_alpha': 0.6,
        'beta_start':       0.4,
        'beta_frames':      100000,
        'n_steps':          3,
        'learning_rate': 0.00025,
        'gamma': 0.99,
        'batch_size': 32
    },
    'doom': {
        'env_name': "VizdoomCorridor-v0",
        'stop_reward': 1000.0,
        'run_name': 'doom',
        'replay_size': 50000,
        'replay_initial': 10000,
        'target_net_sync': 10000,
        'epsilon_frames': 10 ** 6,
        'epsilon_start': 1.0,
        'epsilon_final': 0.1,
        'prio_replay_alpha': 0.6,
        'beta_start':       0.4,
        'beta_frames':      500000,
        'n_steps':          5,
        'learning_rate': 0.00025,
        'gamma': 0.99,
        'batch_size': 32
    },
}
